baseURL: http://www.thogmedorje.com
theme: hea
title: H.E. Asanga Rinpoche's Website
defaultContentLanguage: en  # en/zh/...
copyright: "Copyright © 2017–2020, H.E. Asanga Rinpoche All Rights Reserved."
footnoteReturnLinkContents: ↩
hasCJKLanguage: true
paginate: 9
background: "https://raw.githubusercontent.com/thogmedorje/up/master/uPic/WechatIMG3527.jpeg"
summaryLength: "10"
enableEmoji: true
googleAnalytics: ""      # UA-XXXXXXXX-X 
permalinks:
  posts: /:year/:month/:filename/

#publishDir: docs

taxonomies:
    category : categories
    tag : tags
    series : series
outputFormats:          # use for search. recommend not to modify 
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true



# sitemap
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    
    - identifier: about
      name: About Rinpoche
      title: About
      url: /about
      weight: 1

    - identifier: posts
      name: posts
      title: Posts
      url: /posts
      weight: 2

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories
      weight: 3

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags
      weight: 4

    - identifier: Chinese
      name: 中文
      title: 中文
      url: /cn
      weight: 5

    

outputs:
  home:
    - HTML
    - RSS
    - JSON
  
params:
  since: 2017
  dateFormatToUse: "2006-01-02"
  enablePostCopyright: false
  contentSharing: "I'm happy for you to share content on this site, but please provide attribution."

  # the directory under content folder that you want to render
  mainSections: ["posts"]
  # Enable/Disable menu icons
  # Icon Reference: http://blog.cofess.com/hexo-theme-pure/iconfont/demo_fontclass.html
  enableMathJax: true #Enable mathjax support, to use mathematical notations
  highlightjs:
    langs: ["python", "javascript"] # refer to http://staticfile.org/, search highlight.js, already have highlight.min.js
  layout: "1"
  
    
  menuIcons:
    enable: true  # 是否启用导航菜单图标
    home: icon-home-fill
    archives: icon-archives-fill
    categories: icon-folder
    tags: icon-tags
    repository: icon-project
    books: icon-book-fill
    links: icon-friendship
    about: icon-cup-fill

  # profile
  profile:
    enabled: true # Whether to show profile bar
    avatar: fwz-hero-2.png
    gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
    author: Khöndung Asanga Vajra Sakya Rinpoche
    author_title:  
    author_description: 
    location: India
    follow: https://
    # Social Links
    social:
      links:
        github: https://github.com/thogmedorje
        # weibo: http://weibo.com/{yourid}
        # twitter: https://twitter.com/
        # facebook: /
        rss: /index.xml
      link_tooltip: false # enable the social link tooltip, options: true, false
  # Site
  site:
    logo:
      enabled: true
      width: 40
      height: 40
      url: favicon.ico
    title: Hugo # 页面title
    favicon: favicon.ico
    board: <p>enjoy hhhh~</p><a href="#">google.com</a> # 公告牌

  # Share
  # weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
  share:
    enable: true # 是否启用分享
    sites: weibo,qq,wechat,facebook,twitter # PC端显示的分享图标
    mobile_sites: weibo,qq,qzone # 移动端显示的分享图标

  # Comment
  comment:
    type:  # type disqus/gitalk/valine 启用哪种评论系统
    disqus: your_disqus_name # enter disqus shortname here
    gitalk: # gitalk. https://gitalk.github.io/
      owner: #必须. GitHub repository 所有者，可以是个人或者组织。
      admin: #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
      repo:  #必须. GitHub repository.
      ClientID: #必须. GitHub Application Client ID.
      ClientSecret: #必须. GitHub Application Client Secret.
    valine: # Valine. https://valine.js.org
      appid: # your leancloud application appid
      appkey: # your leancloud application appkey
      notify: # mail notifier , https://github.com/xCss/Valine/wiki
      verify: # Verification code
      placeholder: enjoy~ # comment box placeholder
      avatar: mm # gravatar style
      meta: nick,mail # custom comment header
      pageSize: 10 # pagination size
      visitor: false # Article reading statistic https://valine.js.org/visitor.html

  # Donate
  donate:
    enable: false
    # 微信打赏
    wechatpay:
      qrcode: donate/wechatpayimg.png
      title: 微信支付
    # 支付宝打赏
    alipay:
      qrcode: donate/alipayimg.png
      title: 支付宝

  # PV
  pv:
    busuanzi:
      enable: false # 不蒜子统计
    leancloud:
      enable: false # leancloud统计
      app_id: # leancloud <AppID>
      app_key: # leancloud <AppKey>

  # wordcount
  postCount:
    enable: true
    wordcount: true # 文章字数统计
    min2read: true # read time 阅读时长预计

  # config
  config:
    skin: # theme color default is white. other type [theme-black,theme-blue,theme-green,theme-purple]
    layout: main-center # main-left main-center main-right
    excerpt_link: Read More
    toc: true

  # Sidebar
  sidebar: right

  # Search
  search:
    enable: true # enable search. thanks for https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/master/source/js/insight.js

  # Sidebar only the following widgets. you can remove any you don't like it.
  widgets:
   # - board
    - category
    - tag
    - recent_posts

  instafeed:
    enable: true
    user_id: '4044026246'
    access_token: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/headroom/headroom.js
      - link: plugins/instafeed/instafeed.min.js
      - link: plugins/masonry/masonry.js
      - link: plugins/reading-time/readingTime.min.js
      - link: plugins/smooth-scroll/smooth-scroll.js
      - link: plugins/search/fuse.min.js
      - link: plugins/search/mark.js
      - link: plugins/search/search.js


languages:
  en:
    languageName: English
    title: Khöndung Asanga Vajra Sakya Rinpoche
    languageCode: "en"
    weight: 1
  cn:
    languageName: 中文
    title: 萨迦无著金刚仁波切
    languageCode: "cn"
    weight: 2
    menu:
      main:
        - identifier: home
          name: 首页
          title: Home 
          url: /cn
          weight: 1

        - identifier: posts
          name: 教言
          title: 教言
          url: /cn/posts
          weight: 2

        - identifier: categories
          name: 分类
          title: categories
          url: /cn/categories
          weight: 3

        - identifier: tags
          name: 标签
          title: Tags
          url: /cn/tags
          weight: 4

        - identifier: about
          name: 传承
          title: About
          url: /cn/about
          weight: 5

        - identifier: English
          name: English
          title: English
          url: /
          weight: 6

